import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import vuePlugin from 'esbuild-plugin-vue3';
import { watchFile } from 'fs';
import { readFile, writeFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import postcss from 'postcss';
import tailwindPostcss from '@tailwindcss/postcss';
import autoprefixer from 'autoprefixer';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const projectRoot = dirname(fileURLToPath(import.meta.url));
const baseStylesPath = join(projectRoot, 'styles.base.css');
const componentStylesPath = join(projectRoot, 'main.css');
const tailwindEntryPath = join(
	projectRoot,
	'modules/core/ui-vue/styles/tailwind.css'
);
const outputStylesPath = join(projectRoot, 'styles.css');

/**
 * @description Компилирует Tailwind через PostCSS (`@tailwindcss/postcss`).
 * @returns {Promise<string>} Скомпилированный CSS или пустая строка при ошибке.
 */
async function compileTailwindCss() {
	const input = await readFile(tailwindEntryPath, 'utf8');
	const result = await postcss([tailwindPostcss, autoprefixer]).process(input, {
		from: tailwindEntryPath,
	});
	return result.css;
}

/**
 * @description Синхронизирует итоговый `styles.css` из базовых стилей, Tailwind и CSS,
 * сгенерированного Vue SFC сборкой. Это гарантирует, что Obsidian увидит все стили,
 * потому что загружает только `styles.css`.
 * @returns {Promise<void>}
 */
async function syncPluginStyles() {
	const base = await readFile(baseStylesPath, 'utf8');
	let componentCss = '';

	try {
		componentCss = await readFile(componentStylesPath, 'utf8');
	} catch {
		componentCss = '';
	}

	let tailwindCss = '';
	try {
		tailwindCss = await compileTailwindCss();
	} catch (error) {
		console.warn('[kora] Tailwind compile failed:', error);
	}

	const banner = `/*\nGenerated file.\nDo not edit manually: run build/dev to regenerate from styles.base.css + tailwind + main.css\n*/\n\n`;
	const chunks = [banner, base.trim()];
	if (tailwindCss.trim()) {
		chunks.push('\n\n/* Tailwind (PostCSS) */\n', tailwindCss.trim());
	}
	if (componentCss.trim()) {
		chunks.push('\n\n/* Vue SFC compiled styles */\n', componentCss.trim());
	}
	await writeFile(outputStylesPath, chunks.join(''), 'utf8');
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['apps/obsidian-plugin/src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		vuePlugin({
			extractCss: false,
		}),
	],
	loader: {
		'.tl': 'text',
	},
});

if (prod) {
	await context.rebuild();
	await syncPluginStyles();
	process.exit(0);
} else {
	await context.watch();
	await syncPluginStyles();

	const reSync = () => {
		void syncPluginStyles();
	};
	watchFile(componentStylesPath, { interval: 300 }, reSync);
	watchFile(tailwindEntryPath, { interval: 300 }, reSync);
	watchFile(baseStylesPath, { interval: 300 }, reSync);
}
